### ISSUE TITLE
Bug: Potions don't apply unless sword/axe is in offhand.

### ISSUE THREAD

**Issue by Akitori** [Lucid-Lucie/Alchemist#2] opened 2021-01-14 07:45 UTC
Howdy! I've been testing the mod, was confused when the first sword i tried it with didn't work. I tried left clicking, right clicking, then swapping to offhand.

swapping to offhand lets me use my mainhand weapon while applying the effects from the offhand. Really really neat, buttt I doub that's the effect you're going for.

Though that would be incredibly useful for shields.

Anyhow yeah, latest release, forge35.1.28

**Comment by Lucid-Lucie** [comment] 2021-01-14 08:54
If I understand you right it is the correct way.

Intended way is: Potion in off hand, Tool in main hand. Tool does a "use" animation and bottle changes to empty.
Timestamp of a showcase showing the correct way: https://youtu.be/Xz9Q1UV5-jQ?t=43

Did this answer your question or did I misunderstand you?

**Comment by Akitori** [comment] 2021-01-14 13:46
https://youtu.be/nzvWo-am9EM

dis. only stops doing this on a world reload.

**Comment by Lucid-Lucie** [comment] 2021-01-14 14:25
Thank you for the video!

I've tried to replicate it without any success. My theory is that some other mod screws up "LivingHurtEvent" that the mod uses to apply the effect. Only way I can further check the issue is if you send a mod list or a zip with all the mods used (Preferably a zip because then I have the exact same setup to test)

**Comment by Akitori** [comment] 2021-01-15 03:42
It seems unusually difficult to replicate. 

here's the entire Zip.

https://www.dropbox.com/s/qkqwkb4wzbbhusu/testing.zip?dl=0

i will continue testing to figure out what causes it.

**Comment by Lucid-Lucie** [comment] 2021-01-16 12:18
I've replicated the bug and I am now working on a fix.

**Comment by Lucid-Lucie** [comment] 2021-01-16 16:12
The bug was that active hand could randomly be set to off hand. Fixed in version 2.0.1.

**Closed by Lucid-Lucie** 2021-01-16 16:12 UTC
Labels: bug
